---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  cachier: machine
  parallel: true
platforms:
  - name: dc
    box: jtarpley/${MOLECULE_BOX:-w2022_cis}
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: dfs_replication_
    groups:
      - windows
      - windows_domain
  - name: fs1
    box: jtarpley/${MOLECULE_BOX:-w2022_cis}
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: dfs_replication_
    groups:
      - subjects
      - windows
      - windows_domain
      - windows_domain_members
  - name: fs2
    box: jtarpley/${MOLECULE_BOX:-w2022_cis}
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: dfs_replication_
    groups:
      - subjects
      - windows
      - windows_domain
      - windows_domain_members
provisioner:
  name: ansible
  inventory:
    group_vars:
      subjects:
        dfsr_admin_user: TEST\vagrant
        dfsr_admin_password: vagrant
        dfsr_groups:
          - name: TestReplication
            members:
              - FS1.test.loc
              - FS2.test.loc
            folders:
              - name: Replica1
                path: C:\Replica1
              - name: Replica2
                path: C:\Replica2
      windows:
        ansible_shell_type: powershell
        ansible_become_method: runas
        ansible_become_user: SYSTEM
    host_vars:
      fs1:
        ansible_user: TEST\vagrant
        dfsr_default_primary_member: true
      fs2:
        ansible_user: TEST\vagrant
verifier:
  name: ansible
