---
- name: Validate DFS Replication folders are local paths
  ansible.builtin.assert:
    that:
      - _dfsr_folder.path | regex_search('^[a-zA-Z]:')
    fail_msg: The DFS Replication folder path must be a local path.
    success_msg: The DFS Replication folder path is a local path.

- name: Check that the drive exists
  ansible.windows.win_powershell:
    script: |
      [CmdletBinding()]
      param (
        [string]$DriveLetter
      )

      $Ansible.Changed = $false

      try {
        $drive = Get-PSDrive -Name $DriveLetter

        if ($drive.Root.StartsWith($DriveLetter)) {
          $Ansible.Result = $true
        }
        else {
          $Ansible.Result = $false
        }
      }
      catch { 
        $Ansible.Result = $false
        Write-Debug $_
      }
    parameters:
      DriveLetter: "{{ _dfsr_folder.path | win_splitdrive | first | regex_search('^[a-zA-Z]') }}"
  register: _dfsr_drive_exists

- name: Validate that the DFS Replication folder path is on an existing drive
  ansible.builtin.assert:
    that:
      - _dfsr_drive_exists.result
    fail_msg: The DFS Replication folder path must be on an existing local drive.
    success_msg: The DFS Replication folder path is on an existing local drive.
