---
argument_specs:
  main:
    short_description: DFS Replication
    description:
      - This role configures DFS Replication on a Windows Server machine.
    author: Jim Tarpley (@trippsc2)
    options:
      dfsr_admin_user:
        type: str
        required: true
        description:
          - The user account to be used when configuring DFS Replication.
      dfsr_admin_password:
        type: str
        required: true
        no_log: true
        description:
          - The password for the *dfs_admin_user* user account.
      dfsr_default_primary_member:
        type: bool
        required: false
        description:
          - Whether the server should default to being the primary member for folders in DFS Replication groups.
      dfsr_default_read_only:
        type: bool
        required: false
        default: false
        description:
          - Whether the server should default to being a read-only member for folders in DFS Replication groups.
      dfsr_groups:
        type: list
        required: true
        elements: dict
        description:
          - A list of DFS Replication groups to configure.
        options:
          name:
            type: str
            required: true
            description:
              - The name of the DFS Replication group to configure.
          primary_member:
            type: bool
            required: false
            description:
              - Whether the server should default to being the primary member for folders in this DFS Replication group.
          read_only:
            type: bool
            required: false
            description:
              - Whether the server should default to being a read-only member for folders in this DFS Replication group.
          folders:
            type: list
            required: true
            elements: dict
            description:
              - A list of folders to configure in this DFS Replication group.
            options:
              name:
                type: str
                required: true
                description:
                  - The name of the folder to configure.
              path:
                type: path
                required: true
                description:
                  - The local path of the folder.
              primary_member:
                type: bool
                required: false
                description:
                  - Whether the member server is the primary member for the folder.
                  - This defaults to the *primary_member* value for the group or the *dfsr_default_primary_member* value in that order.
              read_only:
                type: bool
                required: false
                description:
                  - Whether the member server is read-only for the folder.
                  - This defaults to the *read_only* value for the group or the *dfsr_default_read_only* value in that order.
              staging_quota:
                type: int
                required: false
                default: 4096
                description:
                  - The staging quota for the folder in MB.
                  - This should be equal to the sum of the sizes of the largest 32 files to be replicated.
          members:
            type: list
            required: true
            elements: str
            description:
              - A list of the fully qualified domain names (FQDN) of the member servers of this DFS Replication group.
