---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: replication
  description: This role configures DFS Replication on a Windows Server machine.

  license: MIT

  min_ansible_version: '2.15'

  platforms:
    - name: Windows
      versions:
        - '2019'
        - '2022'

collections:
  - ansible.windows
  - community.windows
  - trippsc2.windows

dependencies:
  - role: trippsc2.windows.install_psgallery
