---
galaxy_info:
  author: Jim Tarpley
  namespace: trippsc2
  role_name: replication
  description: This role configures DFS Replication on a Windows Server machine.

  license: MIT

  min_ansible_version: '2.14'

  platforms:
    - name: Windows
      versions:
        - '2019'
        - '2022'

collections:
  - ansible.windows
  - community.windows
  - trippsc2.general

dependencies: []
