---
- name: Ensure 'DFSDsc' PowerShell module is installed
  community.windows.win_psmodule:
    name: DFSDsc
    state: present

- name: Install DFS Replication feature
  ansible.windows.win_feature:
    name:
      - FS-DFS-Replication
    include_management_tools: true
    state: present
